### PR TITLE
Eperez reset pw

### PR DESCRIPTION
**Pull request by enriquepablo**
* DB classes for the reset password app: User and UserDB, States and StateDB's
* Deprecation for the old classes (used by the security app)
* Tests

### CODE REVIEW

**Comment by enriquepablo** [comment]
Some problem deprecating classes - the db classes in security are not tested :(

**Comment by enriquepablo** [comment]
deprecating methods rather than classes

**Comment by johanlundberg** [comment]
I think a bump to version is needed before merging.

**Comment by enriquepablo** [comment]
> I think a bump to version is needed before merging.

Yes you're right, done

**Pull request merged**
